irisnet/explorer

server/Dockerfile, server/Makefile, setup/docker-compose.yml, setup/start.sh, ui/Dockerfile, ui/package.json
=> add docker

server/modules/rpc/account.go, server/modules/rpc/block.go, server/modules/rpc/doc.md, server/modules/rpc/stake.go, server/modules/rpc/tx.go, server/modules/store/m/account_m.go, server/modules/store/m/coin_tx_m.go, server/modules/store/m/stake_tx_m.go, server/modules/tools/common.go, ui/src/api/Tx.js
=> 1：修改分页查询条件,增加分页参数[pagesize]

server/modules/rest/tx.go, server/modules/store/m/coin_tx_m.go, server/modules/store/state.go, server/modules/store/types.go
=> ####修改交易历史查询接口并优化查询mongodb的方法

server/modules/rest/tx.go, setup/start.sh
IRISE-18
2:发布脚本优化(原因:服务器没有编译环境，只能先本地打包，上传，在发布。现在将发布流程命令分解)
=> 1:bug fix :优化交易查询rest接口时，参数校验错误，导致部分交易查询不到

ui/src/api/Account.js, ui/src/components/Account/CoinTxs.js
=> IRISXP-17 浏览器不能查询个人历史交易记录bug

frontend/src/components/FaucetPage.vue
=> Device adapter

frontend/src/components/EchartsValidatorsLine.vue
=> #IRISXP-123

frontend/src/components/BlocksListPage.vue
【stake Transactions】列表中amount值显示为0问题
=> #IRISXP-107

frontend/src/components/NodePage.vue
=> #IRISXP-140

frontend/src/components/EchartsValidatorsLine.vue
=> #IRISXP-121

frontend/src/components/AddressPage.vue
=> #IRISXP-147

frontend/src/components/AddressPage.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/views/Home.vue
hackthon irishub explorer 测试问题
=> #IRISXP-142

frontend/src/components/AppHeader.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue
=> #IRISXP-128

frontend/src/components/AddressPage.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue
=> #IRISXP-160

frontend/public/index.html, frontend/src/App.vue, frontend/src/common/Tools.js, frontend/src/components/AppHeader.vue, frontend/src/components/FaucetPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/router.ts
Proposal列表页的展示
#IRISXP-176
Proposal详情页的展示
#IRISXP-169
header头部鼠标无法滚动页面
#IRISXP-163
水龙头领取失败原因展示
#IRISXP-149
【通用】分页按钮显示问题
=> #IRISXP-175

frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue
【验证人详情】历史区域图验证人slash后再恢复之后的显示不正确
=> #IRISXP-178

frontend/src/components/AddressPage.vue
=> #IRISXP-180

frontend/src/components/AddressPage.vue
=> #IRISXP-184

frontend/src/common/Tools.js, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue
=> #IRISXP-195

frontend/src/components/AddressPage.vue, frontend/src/components/BlocksDetail.vue
=> #IRISXP-198

frontend/src/components/AddressPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/table/BlocksListTable.vue
=> #IRISXP-210

frontend/src/components/BlocksListPage.vue
=> #IRISXP-211

frontend/src/components/AddressPage.vue
=> #IRISXP-213

backend/task/task.go
IRISXP-212:统计validator在线率时，如果在线率等于0，需要区别出当前是否validator
=>  IRISXP-212:统计validator在线率时，如果在线率等于0，需要区别出当前是否validator

frontend/src/components/AddressPage.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue
【Validators】详情中uptime图中的最后一个点显示不正确
=> #IRISXP-232

frontend/src/components/AppHeader.vue, frontend/src/components/NodesPage.vue, frontend/src/router.ts, frontend/src/style/mixin.scss, frontend/src/style/reset.scss
=> #IRISXP-228

frontend/src/components/FaucetPage.vue
=> #IRISXP-216

frontend/src/components/EchartsValidatorsUpTimeLine.vue
=> #IRISXP-237

frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/NodesPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/views/Home.vue
=> #IRISXP-217

frontend/src/components/AddressPage.vue
【Validators】验证人没在线时间段的uptime图显示不正确
=> #IRISXP-238

frontend/src/components/BlocksListPage.vue, frontend/src/components/table/BlocksListTable.vue
=> #IRISXP-221

frontend/src/components/AddressPage.vue
=> #IRISXP-226

frontend/src/components/BlocksDetail.vue
=> #IRISXP-218

frontend/src/components/AddressPage.vue, frontend/src/components/BlocksDetail.vue
=> #IRISXP-225

frontend/src/main.ts
=> #IRISXP-281

frontend/src/components/BlocksDetail.vue
【Block】区块详情中切换前后区块后各类型交易列表没有刷新问题
=> #IRISXP-283

frontend/src/components/FaucetPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue
【通用】列表中如果proposal id没有的话应该显示--不应该显示0
=> #IRISXP-286

frontend/src/components/AddressPage.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/views/Home.vue
【Block】区块详情中Declaration类型交易列表Self Bond值显示不正确
=> #IRISXP-284

frontend/src/components/FaucetPage.vue, frontend/src/main.ts
=> #IRISXP-287

frontend/src/components/AppHeader.vue
【Block】区块详情中BeginRedelegate和BeginUnbonding类型的值显示不正确
=> #IRISXP-290

frontend/src/components/AddressPage.vue, frontend/src/components/EchartsValidatorsLine.vue
【验证人详情】votingpower 最近14天图超过100时没显示问题
=> #IRISXP-302

frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/FaucetPage.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/NodesPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/views/Home.vue
=> #IRISXP-299

frontend/src/common/Tools.js, frontend/src/components/BlocksListPage.vue, frontend/src/components/EchartsPie.vue, frontend/src/components/NodesPage.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/views/Home.vue
=> #IRISXP-300

frontend/src/components/AddressPage.vue, frontend/src/components/BlocksDetail.vue
=> #IRISXP-310

frontend/src/components/PrivacyPolicy.vue
=> #IRISXP-329

frontend/src/components/EchartsPie.vue, frontend/src/views/Home.vue
=> #IRISXP-331

frontend/src/components/TransactionsDetail.vue
【交易详情】提议类型的交易详情中InitialDeposit显示不正确
=> #IRISXP-335

frontend/package.json, frontend/src/registerServiceWorker.ts
=> #IRISXP-322

frontend/src/components/FaucetPage.vue
=> #IRISXP-340

frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/NodesPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/style/mixin.scss, frontend/src/views/Home.vue
=> #IRISXP-313

frontend/src/common/Tools.js, frontend/src/components/TransactionsDetail.vue
=> #IRISXP-312

frontend/src/components/searchResult.vue
=> #IRISXP-352

frontend/src/components/EchartsPie.vue, frontend/src/views/Home.vue
=> #IRISXP-354

frontend/src/components/FaucetPage.vue, frontend/src/components/searchResult.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/style/mixin.scss
=> #IRISXP-356

frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/table/BlocksListTable.vue
=> #IRISXP-316

frontend/src/App.vue, frontend/src/common/Tools.js, frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/PrivacyPolicy.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/views/Home.vue
=> #IRISXP-372

frontend/src/App.vue, frontend/src/components/AddressPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/TransactionsDetail.vue
=> #IRISXP-377

frontend/src/common/Tools.js, frontend/src/components/AddressPage.vue, frontend/src/components/BlocksListPage.vue
【验证人详情】voting power值的最后一位小数显示不正确问题
=> #IRISXP-381

frontend/src/App.vue, frontend/src/common/Tools.js, frontend/src/components/BackToTop.vue, frontend/src/components/FaucetPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/views/Home.vue
=> #IRISXP-383

frontend/src/components/AddressPage.vue, frontend/src/components/TransactionsDetail.vue
=> #IRISXP-386

frontend/src/components/ProposalsPage.vue
【Proposals】列表字段没有移除「Submit Block」「Voting Start Block」字段
=> #IRISXP-395

frontend/src/common/Tools.js, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/TransactionsDetail.vue
【Governance】列表中fee没有显示问题以及赞助类型的交易没显示popsalid问题
=> #IRISXP-401

frontend/src/components/AppHeader.vue, frontend/src/main.ts
=> #IRISXP-399

frontend/src/common/Tools.js, frontend/src/components/AddressPage.vue, frontend/src/components/TransactionsDetail.vue
=> #IRISXP-405

frontend/src/components/version.vue, frontend/src/router.ts
=> #IRISXP-392

frontend/src/components/BlocksDetail.vue
=> #IRISXP-415

frontend/src/components/FaucetPage.vue
=> #IRISXP-427

frontend/src/components/FaucetPage.vue
首页Block、Transaction时间展示调整，展示距离当前时间的长短。
=> #IRISXP-440

frontend/src/components/AddressPage.vue
=> #IRISXP-442

frontend/src/components/AddressPage.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/FaucetPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/constant/Constant.js, frontend/src/main.ts, frontend/src/util/Tools.js
=> #IRIS浏览器IRISXP-449

frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/main.ts, frontend/src/style/mixin.scss, frontend/src/util/Tools.js, frontend/src/views/Home.vue
首页Block，Transactions，Validators，Voting Power字段新增渐显效果
=> #IRISXP-450

website/upgrade/css/upgrading.css
=> #IRISXP-455

backend/lcd/keys.go, backend/lcd/stake.go, backend/lcd/tendermint.go, backend/lcd/types.go, backend/model/stake.go, backend/service/service_candidate.go, backend/utils/common.go
=> IRISXP-474:http://jira.bianjie.ai/browse/IRISXP-474

frontend/src/App.vue
=> #IRISXP-479

backend/rest/controller/home.go, backend/service/service_candidate.go, backend/types/decimal.go, backend/utils/bech32.go
=> IRISXP-558: add field "moniker,operator" for navigation api

frontend/src/components/BlocksDetail.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/table/BlocksListTable.vue
=> Display different fields based on validator status

frontend/src/components/BlocksListPage.vue
=> validator list pagination fix

frontend/src/components/AppHeader.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/EchartsPie.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/router.ts, frontend/src/store.ts
=> Refact ValidatorListPage

frontend/src/components/AppHeader.vue, frontend/src/components/BlocksListPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/router.ts
=> Add Governance navigation

frontend/src/components/ParametersPage.vue, frontend/src/components/table/ParametersTable.vue, frontend/src/constant/Constant.js
=> Add Parameters Page

frontend/src/components/ParametersPage.vue
=> Parameter display optimization

frontend/src/components/ParametersPage.vue, frontend/src/components/table/ParametersTable.vue, frontend/src/util/Tools.js
=> Update Unbonding Time

frontend/src/components/ParametersPage.vue, frontend/src/components/table/ParametersTable.vue
=> Fix calculation rule

frontend/src/router.ts
=> Remove history mode

frontend/src/components/ParametersPage.vue
=> update Parameters Title

frontend/src/components/AppHeader.vue, frontend/src/components/RichList.vue, frontend/src/router.ts, frontend/src/util/Tools.js
=> Add rich list navigation

frontend/src/components/RichList.vue
=> Fixed the maximum parameter of the toFixed method

frontend/src/components/RichList.vue
=> Update description of amount

frontend/src/util/Tools.js
=> Fix page jump cannot return to top

frontend/src/components/BlocksDetail.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/components/table/ValidatorListTable.vue
=> Update the accuracy of votingpower and add unbonding height unbonding time

frontend/src/components/ValidatorListPage.vue
=> Update displays with null values

frontend/src/components/BlocksDetail.vue, frontend/src/components/table/ValidatorListTable.vue
=> Adjust the delegator Number field presentation

frontend/src/components/BlockInfo.vue
=> R4R: refactor blockdetail page

frontend/src/components/table/BlockDetailListTable.vue
=> R4R: refactor blockdetail list table

frontend/src/components/table/BlockDetailListTable.vue
=> R4R: Adjust the location of the governance list field

frontend/src/components/BlockInfo.vue, frontend/src/components/table/BlockDetailListTable.vue
=> R4R: Fixed some transactions not shown in the list

frontend/src/components/table/BlockDetailListTable.vue
=> R4R: Failed governance transaction cannot jump to detail page

frontend/src/components/table/BlocksListTable.vue, frontend/src/components/table/TxListPageTable.vue, frontend/src/util/Tools.js
=> R4R: Stake list add tx_signer field

frontend/src/components/table/BlockDetailListTable.vue, frontend/src/components/table/TxListPageTable.vue
=> R4R:Fix click fail governance list title jump to proposal detail page

frontend/src/components/table/BlockDetailListTable.vue, frontend/src/components/table/TxListPageTable.vue, frontend/src/util/Tools.js
=> R4R:   delete from and  to field in declaration list 

backend/lcd/keys_test.go, backend/lcd/stake_test.go, backend/lcd/tendermint_test.go, backend/lcd/types.go
=> R4R: adapt to lcd break changes defined in irishub v0.14.0

backend/service/service_tx.go
=> 交易列表接口一次查询不同交易类型需要附件的字段；proposal vote 和 deposit 增加了title proposalType desc。

backend/rest/controller/tx.go, backend/service/service_tx.go
add query condition field(signers->addr_bech32) in the tx list
swap the values of from and to in the redelegate  tx.
=> add query condition field(signers->addr_bech32) in the tx list.

backend/rest/controller/tx.go, backend/service/service_tx.go
fix statistics api condition(signers).
=> remove fields(from,to)  in the Declaration tx list。

backend/model/tx.go, backend/service/service_tx.go
Resolves: #604 
Resolves: #605
=> R4R: set the values of fields(from,to) by tx.tags in the withdraw rewards tx.

backend/service/service_tx.go
Fixes: #604
Fixes: irisnet/explorer#605
=> R4R: Show the different value of the field(withdrawReward from) in the tx list and one tx.

frontend/src/components/table/BlockDetailListTable.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/components/table/TxListPageTable.vue
=> R4R:  Multiaddress display in stake list form field

frontend/src/components/AddressPage.vue, frontend/src/components/BlockInfo.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/components/table/BlockDetailListTable.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/components/table/TxListPageTable.vue, frontend/src/util/Tools.js
=> R4R:Fix the form field showing 0 in stake list

backend/service/service_tx.go
=> get value of field(from) from tx.To in the WithdrawDelegatorReward tx list.

backend/orm/document/blacklist.go, backend/orm/document/gov_params.go, backend/orm/document/power_change.go, backend/orm/document/uptime_change.go, backend/orm/document/validator.go, backend/script/mongodb.js, backend/service/service_candidate.go, backend/task/uptime_change.go
=> R4R: add prefix for tables which created by explorer-backend

backend/lcd/gov.go, backend/lcd/gov_test.go, backend/lcd/tendermint.go, backend/lcd/tendermint_test.go, backend/lcd/types.go, backend/orm/document/gov_params.go, backend/rest/controller/governance.go, backend/script/mongodb.js, backend/service/service_gov_params.go, backend/service/service_gov_params_test.go, backend/task/gov_params.go, backend/task/types.go
=> R4R: update the governance parameter api.

backend/model/proposal.go, backend/orm/document/validator.go, backend/rest/controller/governance.go, backend/service/service_proposal.go, backend/service/service_proposal_test.go, backend/types/const.go, backend/utils/bech32_test.go
=> R4R: add query proposal vote txs api and deposit txs api

backend/README.md, backend/rest/controller/common.go
=> update get explorer config api

frontend/src/components/AppHeader.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/components/table/ValidatorListTable.vue, frontend/src/constant/Constant.js
=> R4R:refactor network menu logic

backend/service/proposal_test.go, backend/service/service_proposal.go
=> R4R:query proposals order by votingEndTime ASC in the QueryDepositAndVotingProposalList api.

frontend/src/components/ProposalsDetail.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/components/TxListPage.vue, frontend/src/components/table/MTxListPageTable.vue, frontend/src/util/Tools.js
=> R4R: Update tx list table compontens

backend/lcd/gov.go, backend/service/service_gov_params.go, backend/service/service_gov_params_test.go
=> R4R: update module param description.

frontend/src/views/Home.vue
=> R4R:Home latest block add details link and bonded tokens add total token

backend/model/proposal.go, backend/orm/document/validator.go, backend/service/service_proposal.go, backend/service/service_proposal_test.go
=> get voter voting power from latest validator set when proposal status is votingPeriod

backend/model/proposal.go, backend/orm/document/validator.go, backend/service/service_proposal.go, backend/service/service_proposal_test.go
=> R4R: Hotfix/0.9.7

backend/lcd/lite/swagger-ui/swagger.yaml, backend/model/block.go, backend/orm/document/base.go, backend/orm/document/block.go, backend/orm/document/block_test.go, backend/orm/document/validator.go, backend/orm/mongo.go, backend/rest/controller/block.go, backend/service/service_block.go, backend/service/service_block_test.go, backend/types/const.go
update the blocklist API,
add the latest block height API.
fix : #724
=> R4R: update the block list API,

frontend/src/components/HomeBlockModule.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/commonComponents/MParametersCard.vue, frontend/src/components/commonComponents/MProposalsCard.vue, frontend/src/components/commonComponents/MProposalsEchart.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/table/BlockDetailListTable.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/components/table/MProposalsDetailTable.vue, frontend/src/components/table/MProposalsListTable.vue, frontend/src/components/table/MTxListPageTable.vue, frontend/vue.config.js
all pages hover tooltip style change #735
=> R4R:all pages tooltip style change

frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlockListPage.vue, frontend/src/components/BlocksDetail.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/commonComponents/MProposalsCard.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/searchResult.vue, frontend/src/components/table/BlocksListTable.vue, frontend/vue.config.js
reset the field(stake tx From ) value. #736
=> R4R:some responese field change to lowcase

backend/lcd/lite/swagger-ui/swagger.yaml, backend/model/common.go, backend/model/stake.go, backend/model/tx.go, backend/orm/document/block.go, backend/orm/document/validator.go, backend/orm/document/validator_test.go, backend/rest/controller/common.go, backend/rest/controller/stake.go, backend/service/service_block.go, backend/service/service_common.go, backend/service/service_tx.go, backend/service/service_validator.go, backend/service/service_validator_test.go, backend/types/const.go, backend/utils/bech32_test.go
1 、resolved: #736
2、query the pre-commit validators from LCD as the latest block(in the database) pre-commit vote.
=> update  swagger document and  2 features.

frontend/src/components/table/MTxListPageTable.vue
Declaration List title error(Amount ->Self_Bonded)
=> R4R: Fix bug (Amount -> Self_Bonded)

backend/orm/document/power_change.go, backend/orm/document/uptime_change.go, backend/orm/document/validator.go, backend/service/service_validator.go, backend/task/uptime_change.go
=> R4R: fix chart by uptime and power.

frontend/src/api/index.js, frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/ParametersPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/RichList.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/components/TxListPage.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/components/searchResult.vue
=> R4R: Refactor richList page interface

backend/lcd/lite/swagger-ui/swagger.yaml, backend/lcd/stake.go, backend/lcd/stake_test.go, backend/lcd/types.go, backend/model/common.go, backend/model/proposal.go, backend/model/stake.go, backend/model/tx.go, backend/orm/document/proposal.go, backend/orm/document/tx.go, backend/orm/document/validator.go, backend/rest/controller/stake.go, backend/service/service_common.go, backend/service/service_tx.go, backend/service/service_validator.go, backend/service/service_validator_test.go, backend/types/const.go, backend/utils/coin.go
=> R4R: Feature/0.9.8

frontend/src/components/ValidatorDetail.vue
=> R4R:Validator detail identity add keyBase link

backend/orm/document/validator.go
=> R4R: fix proposal list api doesn't return totalVotingPower field

backend/service/service_proposal.go, backend/service/service_proposal_test.go
=> R4R: fix get systemVotingPower by get sum of bonded validator's votingPower

backend/task/uptime_change.go
=> fix chart by uptime.

frontend/.editorconfig, frontend/src/components/table/MProposalsListTable.vue
=> R4R: proposal title add jump link on proposal list page

backend/orm/document/tx.go, backend/orm/document/tx_test.go, backend/task/tx_num_group_by_day.go
=> fix the bug about function GetTxCountByDuration

backend/orm/document/validator.go, backend/service/service_delegator.go, backend/service/service_validator.go
=> fix the bug about function QueryDelegation of DelegatorService

frontend/package.json
=> R4R: update package.json

frontend/src/components/ProposalsDetail.vue
=> R4R:proposal description support rich text

frontend/src/App.vue, frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlockListPage.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/RichList.vue, frontend/src/components/TokenStats.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/components/ValidatorDetail.vue, frontend/src/components/commonComponents/MPagination.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/commonComponents/MTabs.vue, frontend/src/components/searchResult.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/components/table/MProposalsDetailTable.vue, frontend/src/components/table/ParametersTable.vue, frontend/src/components/table/TopListTable.vue, frontend/src/components/table/TxListPageTable.vue, frontend/src/components/table/ValidatorListTable.vue, frontend/src/skinStyle/index.js, frontend/src/views/Home.vue
=> R4R: change explorer skin style

frontend/src/components/AppHeader.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/RichList.vue, frontend/src/components/table/MProposalsListTable.vue, frontend/src/components/table/TopListTable.vue, frontend/src/main.ts
=> R4R:Table header fixed

frontend/src/App.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlockInfo.vue, frontend/src/components/BlockListPage.vue, frontend/src/components/BondedTokens.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/EchartsValidatorsUpTimeLine.vue, frontend/src/components/ErrorPage.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/PrivacyPolicy.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/RichList.vue, frontend/src/components/TokenStats.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/components/ValidatorDetail.vue, frontend/src/components/clearStorageHelpPage.vue, frontend/src/components/commonComponents/MPagination.vue, frontend/src/components/commonComponents/MParametersCard.vue, frontend/src/components/commonComponents/MProposalsCard.vue, frontend/src/components/commonComponents/MProposalsEchart.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/commonComponents/MTokenStatsEchart.vue, frontend/src/components/searchResult.vue, frontend/src/components/table/BlocksListTable.vue, frontend/src/components/table/ParametersTable.vue, frontend/src/components/table/ValidatorListTable.vue, frontend/src/router.ts, frontend/src/skinStyle/index.js, frontend/src/views/Home.vue
=> R4R:change explorer skin style

frontend/src/components/AppHeader.vue
=> R4R:Refactor navigation

frontend/src/api/index.js, frontend/src/components/AllTxTypeList.vue, frontend/src/components/AppHeader.vue, frontend/src/components/EchartsLine.vue, frontend/src/components/EchartsPie.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/table/MAllTxTypeListTable.vue, frontend/src/router.ts, frontend/src/views/Home.vue
=> R4R: add a list page that contains all transaction types

frontend/src/components/AllTxTypeList.vue, frontend/src/components/commonComponents/MPagination.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/table/MValidatorListTable.vue
=> R4R:add a list page that contains all transaction types

backend/lcd/asset.go, backend/lcd/asset_test.go, backend/lcd/types.go, backend/model/asset.go, backend/orm/document/asset.go, backend/orm/document/asset_test.go, backend/rest/controller/asset.go, backend/rest/controller/types.go, backend/rest/server.go, backend/script/mongodb.js, backend/service/base_service.go, backend/service/service_asset.go, backend/service/service_asset_test.go, backend/task/asset_tokens.go, backend/task/types.go, backend/types/const.go, frontend/src/components/commonComponents/MTokenStatsEchart.vue
https://github.com/irisnet/explorer/issues/869
=> R4R:asset tokens sync and asset tokens api 

frontend/src/components/AddressPage.vue, frontend/src/components/AppHeader.vue, frontend/src/components/BlockInfo.vue, frontend/src/components/BlockListPage.vue, frontend/src/components/BondedTokens.vue, frontend/src/components/EchartsLine.vue, frontend/src/components/EchartsValidatorsLine.vue, frontend/src/components/FaucetPage.vue, frontend/src/components/GateWayAsset.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/NativeAsset.vue, frontend/src/components/ParametersPage.vue, frontend/src/components/ProposalsDetail.vue, frontend/src/components/ProposalsPage.vue, frontend/src/components/RichList.vue, frontend/src/components/TokenStats.vue, frontend/src/components/TxListPage.vue, frontend/src/components/ValidatorDetail.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/components/commonComponents/MParametersCard.vue, frontend/src/components/commonComponents/MProposalsCard.vue, frontend/src/components/commonComponents/MProposalsEchart.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/commonComponents/MTokenStatsEchart.vue, frontend/src/components/searchResult.vue, frontend/src/components/table/ParametersTable.vue, frontend/src/components/table/ValidatorListTable.vue, frontend/src/skinStyle/index.js, frontend/src/style/address_detail.scss, frontend/src/views/Home.vue
=>  R4R: change explorer skin style

backend/service/service_assets.go, backend/vo/assets.go
[ http://jira.bianjie.ai/browse/IRISXP-745 ]
=> R4R:fix the code about TxFee which should display actualfee

backend/rest/controller/governance.go, backend/types/const.go
=> R4R:Change data source of gov parameters

backend/lcd/tendermint.go, backend/lcd/tendermint_test.go
[ http://jira.bianjie.ai/browse/IRISXP-753 ]
=> R4R:adapt to irishub v0.15 that ParameterChange change to Parameter

backend/service/service_validator.go, backend/vo/stake.go, frontend/src/components/GateWayAsset.vue, frontend/src/components/NativeAsset.vue, frontend/src/components/TransactionsDetail.vue, frontend/src/components/table/MNativeAssetTxListTable.vue
=> update list table fields

backend/lcd/asset.go, backend/lcd/asset_test.go, backend/lcd/bank.go, backend/lcd/types.go, backend/orm/document/asset.go, backend/orm/document/asset_gateway.go, backend/orm/document/config.go, backend/script/mongodb.js, backend/service/service_asset_gateway.go, backend/service/service_assets.go, backend/service/service_proposal_test.go, backend/task/asset_gateway.go, backend/task/types.go
=> R4R:add TotalSupplay and replace Id to TokenId

frontend/src/components/AppHeader.vue, frontend/src/components/GatewayAssetList.vue, frontend/src/components/NativeAssetList.vue, frontend/src/components/table/MAssetListTable.vue, frontend/src/router.ts
=> R4R:add native asset list page and gateway asset list page

frontend/src/api/index.js, frontend/src/components/AssetInformation.vue, frontend/src/components/GateWayAsset.vue, frontend/src/components/GatewayAssetList.vue, frontend/src/components/NativeAsset.vue, frontend/src/components/NativeAssetList.vue, frontend/src/components/table/MAssetListTable.vue, frontend/src/components/table/MNativeAssetTxListTable.vue
=> R4R:add AssetInformation page

frontend/src/api/index.js, frontend/src/components/AssetInformation.vue, frontend/src/components/GatewayAssetList.vue, frontend/src/components/NativeAssetList.vue, frontend/src/components/table/MAssetListTable.vue, frontend/src/router.ts
=> R4R: add asset information page

backend/rest/controller/tx.go, backend/service/service_tx.go, backend/service/service_validator.go, backend/types/const.go, backend/vo/stake.go, backend/vo/tx.go, frontend/.gitignore, frontend/src/components/TransactionsDetail.vue, frontend/src/components/ValidatorDetail.vue, frontend/src/components/ValidatorListPage.vue, frontend/src/util/Tools.js
https://github.com/irisnet/explorer/issues/993
https://github.com/irisnet/explorer/issues/992
https://github.com/irisnet/explorer/issues/991
https://github.com/irisnet/explorer/issues/990
https://github.com/irisnet/explorer/issues/989
=> R4R:for some feature 0.10.2

backend/lcd/gov.go, backend/orm/document/gov_params.go, backend/service/service_gov_params.go, frontend/src/components/ParametersPage.vue, frontend/src/components/commonComponents/MParametersCard.vue
https://github.com/irisnet/explorer/issues/994
https://github.com/irisnet/explorer/issues/987
=> R4R:for asset params add

frontend/src/api/index.js, frontend/src/components/AllTxTypeList.vue, frontend/src/components/TxListPage.vue
=> R4R: add filters to the Txs page

frontend/src/components/AllTxTypeList.vue, frontend/src/components/EchartsLine.vue, frontend/src/components/EchartsPie.vue, frontend/src/components/HomeBlockModule.vue, frontend/src/components/TxListPage.vue, frontend/src/components/ValidatorDetail.vue, frontend/src/components/table/MValidatorDetailTable.vue
=> R4R:optimize the validator information in the validation detail page

backend/conf/config.go, backend/orm/document/blacklist.go, backend/orm/document/blacklist_test.go, backend/orm/document/gov_params.go, backend/rest/controller/task.go, backend/rest/server.go, backend/service/base_service.go, backend/service/base_service_test.go, backend/task/asset_gateway.go, backend/task/asset_tokens.go, backend/task/gov_params.go, backend/task/tx_num_group_by_day.go, backend/task/types.go, backend/task/update_validator.go, backend/task/update_validatoricons.go, backend/types/const.go, backend/utils/common.go, backend/utils/common_test.go, backend/utils/http_client.go
=> R4R: do some improvements

backend/orm/document/tx.go, backend/rest/controller/governance.go, backend/service/service_proposal.go, backend/types/const.go, backend/vo/proposal.go
https://github.com/irisnet/explorer/issues/1022
=> R4R:proposal deposit and voting data api

backend/lcd/tendermint.go, backend/service/service_proposal.go, backend/vo/proposal.go
https://github.com/irisnet/explorer/issues/1033
=> R4R:add new fields for proposal detail api

backend/orm/document/tx.go, backend/orm/document/validator.go, backend/rest/controller/governance.go, backend/service/service_gov_params.go, backend/service/service_proposal.go, backend/vo/proposal.go, frontend/src/components/commonComponents/MProposalsEchart.vue
https://github.com/irisnet/explorer/issues/1035
=> R4R:for proposal detail voters list data api

frontend/src/api/index.js, frontend/src/components/ProposalsDetail.vue, frontend/src/components/commonComponents/MVotingCard.vue
=> R4R:add voting bar for proposal detail

frontend/src/api/index.js, frontend/src/components/ProposalsDetail.vue, frontend/src/components/table/MProposalsDetailTable.vue
=> R4R:add filter for vote tx in proposal detail

backend/service/service_validator.go, backend/service/service_validator_test.go
[http://jira.bianjie.ai/browse/IRISXP-781]
=> R4R:hotfix the bug about selfbond and bondstake compute

backend/conf/config.go, backend/lcd/gov.go, backend/lcd/gov_test.go, backend/lcd/types.go, backend/orm/document/proposal.go, backend/orm/document/tx.go, backend/orm/document/tx_test.go, backend/orm/document/validator_test.go, backend/service/service_proposal.go, backend/task/task_test.go, backend/task/types.go, backend/task/update_proposal_voters.go
=> R4R:add the cron task to update the proposal voters 

frontend/src/components/address/delegator/MAddressInformationTable.vue, frontend/src/components/address/validator/MValidatorListTable.vue
=> R4R:candidate and jailed validator list add sort index

frontend/src/components/block/BlockDetailListTable.vue, frontend/src/components/txs/TxDetail.vue, frontend/src/util/txdetail.js
=> R4R: transaction message from field add moniker 

frontend/src/components/address/delegator/AddressInfomation.vue, frontend/src/components/address/validator/ValidatorDetail.vue, frontend/src/components/commonComponents/MTable.vue, frontend/src/components/commontables/MTable.vue, frontend/src/components/txs/TxDetail.vue, frontend/src/util/Tools.js, frontend/src/util/txdetail.js
=> R4R: refactor the Tx list form field and to field

frontend/src/components/address/delegator/AddressInfomation.vue, frontend/src/components/htlc/HtlcInformation.vue, frontend/src/components/htlc/MHtlsTransferTableList.vue, frontend/src/components/txs/TxDetail.vue, frontend/src/util/Tools.js, frontend/src/util/txdetail.js
=> R4R:refactor the Tx list form field and to field

backend/lcd/stake_test.go, backend/lcd/types.go, backend/rest/server.go, backend/service/service_block.go, backend/task/update_account.go
- additional doesn't log some unimportant err msg
=> R4R: only update account rewards which prefix is "iaa"
